import cart from './cart.js';
cart.addProduct({ name: 'apple', price: 50 });
cart.addProduct({ name: 'lemon', price: 60 });
cart.addProduct({ name: 'lemon', price: 60 });
cart.addProduct({ name: 'grapes', price: 70 });
cart.addProduct({ name: 'strawberry', price: 110 });
cart.increaseQuantity('grapes');
cart.decreaseQuantity('apple');
// cart.remove('lemon');
// cart.clear();
console.log(`Стоимость товаров в корзине: ${cart.countTotalPrice()}`);
console.table(cart.getItems());
